//
//  FBRNViewXMLConverter.h
//  WebDriverAgentLib
//
//  Created by Abhinav Pandey on 22/05/25.
//  Copyright © 2025 Appium. All rights reserved.
//

#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

@class FBXMLGenerationOptions;

/**
 Utility class to convert a React Native UI tree (represented as NSDictionary)
 into an XML string suitable for Appium's getPageSource command.
 */
@interface FBRNViewXMLConverter : NSObject

/**
 Converts the provided React Native UI tree dictionary into an XML string.

 @param rnTree The React Native UI tree, typically generated by RNUiInspector.
 @param options XML generation options (e.g., for masking sensitive values).
 @return An XML string representation of the tree, or nil if conversion fails.
 */
+ (nullable NSString *)xmlStringFromRNTree:(NSDictionary *)rnTree options:(nullable FBXMLGenerationOptions *)options;

@end

NS_ASSUME_NONNULL_END
